# Generated by Django 4.2.13 on 2024-06-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                default="default_profile_pict.jpg", upload_to="users/"
            ),
        ),
    ]
