# Generated by Django 4.2.13 on 2024-06-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                default="users/default_profile_pict.jpeg", upload_to="users/"
            ),
        ),
    ]
